live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/night-owl.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 200, lines = 60 }
padding = { x = 32, y = 32 }
opacity = 1.0
decorations = "None"
startup_mode = "Maximized"

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 11
offset = { x = 0, y = 2 }

